version: '3.3'

services:
  mongo:
    image: mongo:5.0.10
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=guest
      - MONGO_INITDB_ROOT_PASSWORD=guest
      - MONGO_INITDB_DATABASE=project
    ports:
      - '27018:27017'
    volumes:
      - ./docker/mongo-data:/data/db
      - ./docker/mongo-config:/data/configdb

networks:
  dev:
